[build]
builder = "dockerfile"

[deploy]
startCommand = "node server/dist/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
